// Generated by ego.
// DO NOT EDIT

//line http/html/dial.edit.ego:1

package html

import (
	"context"
	"fmt"
	"html"
	"io"

	"github.com/benbjohnson/wtf"
)

type DialEditTemplate struct {
	Dial *wtf.Dial
	Err  error
}

// CancelURL returns the URL to use for the cancel button.
func (tmpl *DialEditTemplate) CancelURL() string {
	if id := tmpl.Dial.ID; id != 0 {
		return fmt.Sprintf("/dials/%d", id)
	}
	return "/dials"
}

func (tmpl *DialEditTemplate) Render(ctx context.Context, w io.Writer) {
	title := "Create Dial"
	if tmpl.Dial.ID != 0 {
		title = "Update Dial"
	}

//line http/html/dial.edit.ego:27
	{
		var EGO App
		EGO.Title = title
		EGO.Yield = func() {
//line http/html/dial.edit.ego:28
			_, _ = io.WriteString(w, "\n\t<div class=\"content\">\n\t\t<form method=\"POST\">\n\t\t\t")
//line http/html/dial.edit.ego:30
			if tmpl.Dial.ID != 0 {
//line http/html/dial.edit.ego:31
				_, _ = io.WriteString(w, "\n\t\t\t\t<input type=\"hidden\" name=\"_method\" value=\"PATCH\"/>\n\t\t\t")
//line http/html/dial.edit.ego:32
			}
//line http/html/dial.edit.ego:33
			_, _ = io.WriteString(w, "\n\n\t\t\t<div class=\"card mb-3\">\n\t\t\t\t<div class=\"card-body\">\n\t\t\t\t\t<h3 class=\"mb-0\">\n\t\t\t\t\t\t")
//line http/html/dial.edit.ego:37
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(title)))
//line http/html/dial.edit.ego:38
			_, _ = io.WriteString(w, "\n\t\t\t\t\t</h3>\n\t\t\t\t</div>\n\t\t\t</div>\n\n\t\t\t")
//line http/html/dial.edit.ego:42
			{
				var EGO Alert
				EGO.Err = tmpl.Err
				EGO.Render(ctx, w)
			}
//line http/html/dial.edit.ego:43
			_, _ = io.WriteString(w, "\n\n\t\t\t<div class=\"card mb-3\">\n\t\t\t\t<div class=\"card-body bg-light\">\n\t\t\t\t\t<div class=\"row\">\n\t\t\t\t\t\t<div class=\"col mb-3\">\n\t\t\t\t\t\t\t<label class=\"form-label\" for=\"name\">Dial Name</label>\n\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"name\" name=\"name\" value=\"")
//line http/html/dial.edit.ego:49
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.Dial.Name)))
//line http/html/dial.edit.ego:49
			_, _ = io.WriteString(w, "\" autofocus maxlength=\"")
//line http/html/dial.edit.ego:49
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(wtf.MaxDialNameLen)))
//line http/html/dial.edit.ego:49
			_, _ = io.WriteString(w, "\"/>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\t\t\t\t<div class=\"card-footer\">\n\t\t\t\t\t<div class=\"row justify-content-end\">\n\t\t\t\t\t\t<div class=\"col-auto align-items-flex-end\">\n\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary mr-1\" role=\"button\" value=\"Save\"/>\n\t\t\t\t\t\t\t<a href=\"")
//line http/html/dial.edit.ego:58
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.CancelURL())))
//line http/html/dial.edit.ego:58
			_, _ = io.WriteString(w, "\" class=\"btn btn-outline-secondary\" role=\"button\">Cancel</a>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</form>\n\t</div>\n")
		}
		EGO.Render(ctx, w)
	}
//line http/html/dial.edit.ego:66
	_, _ = io.WriteString(w, "\n")
//line http/html/dial.edit.ego:66
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
