// Generated by ego.
// DO NOT EDIT

//line http/html/dial_membership.create.ego:1

package html

import (
	"context"
	"fmt"
	"html"
	"io"

	"github.com/benbjohnson/wtf"
)

type DialMembershipCreateTemplate struct {
	Dial *wtf.Dial
}

func (tmpl *DialMembershipCreateTemplate) Render(ctx context.Context, w io.Writer) {

//line http/html/dial_membership.create.ego:13
	{
		var EGO App
		EGO.Yield = func() {
//line http/html/dial_membership.create.ego:14
			_, _ = io.WriteString(w, "\n\t<div class=\"content\">\n\t\t<form method=\"POST\">\n\t\t\t<div class=\"card mb-3\">\n\t\t\t\t<div class=\"card-body\">\n\t\t\t\t\t<h3>\n\t\t\t\t\t\tInvitation\n\t\t\t\t\t</h3>\n\n\t\t\t\t\t<p>\n\t\t\t\t\t\tYou've been invited to contribute to the <strong>")
//line http/html/dial_membership.create.ego:23
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.Dial.Name)))
//line http/html/dial_membership.create.ego:23
			_, _ = io.WriteString(w, "</strong> dial.\n\t\t\t\t\t\tIf you accept, you'll be able to update a WTF level to contribute to the overall WTF level of the dial.\n\t\t\t\t\t</p>\n\t\t\t\t</div>\n\n\t\t\t\t<div class=\"card-footer\">\n\t\t\t\t\t<div class=\"row justify-content-end\">\n\t\t\t\t\t\t<div class=\"col-auto align-items-flex-end\">\n\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" role=\"button\" value=\"Accept Invitation\"/>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</form>\n\t</div>\n")
		}
		EGO.Render(ctx, w)
	}
//line http/html/dial_membership.create.ego:39
	_, _ = io.WriteString(w, "\n")
//line http/html/dial_membership.create.ego:39
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
