// Generated by ego.
// DO NOT EDIT

//line http/html/dial.index.ego:1

package html

import (
	"context"
	"fmt"
	"html"
	"io"
	"net/url"

	"github.com/dustin/go-humanize"

	"github.com/benbjohnson/wtf"
)

type DialIndexTemplate struct {
	Dials  []*wtf.Dial
	N      int
	Filter wtf.DialFilter
	URL    url.URL
}

func (tmpl *DialIndexTemplate) Render(ctx context.Context, w io.Writer) {

//line http/html/dial.index.ego:19
	{
		var EGO App
		EGO.Title = "Your Dials"
		EGO.Yield = func() {
//line http/html/dial.index.ego:20
			_, _ = io.WriteString(w, "\n\t<div class=\"content\">\n\t\t<div class=\"card mb-3\">\n\t\t\t<div class=\"card-body\">\n\t\t\t\t<h3>My Dials</h3>\n\n\t\t\t\t<p class=\"mb-0\">\n\t\t\t\t\t<p>\n\t\t\t\t\t\tDials can be created and shared to monitor the <em>\"what the f**k\"</em> level of a team.\n\t\t\t\t\t</p>\n\n\t\t\t\t\t")
//line http/html/dial.index.ego:30
			if len(tmpl.Dials) == 0 {
//line http/html/dial.index.ego:31
				_, _ = io.WriteString(w, "\n\t\t\t\t\t\t<a href=\"/dials/new\" class=\"btn btn-primary btn-new-dial\" role=\"button\">\n\t\t\t\t\t\t\t<span class=\"fas fa-plus mr-1\"></span>\n\t\t\t\t\t\t\tCreate a new Dial\n\t\t\t\t\t\t</a>\n\t\t\t\t\t")
//line http/html/dial.index.ego:35
			}
//line http/html/dial.index.ego:36
			_, _ = io.WriteString(w, "\n\t\t\t\t</p>\n\t\t\t</div>\n\t\t</div>\n\n\t\t")
//line http/html/dial.index.ego:40
			{
				var EGO Flash
				EGO.Render(ctx, w)
			}
//line http/html/dial.index.ego:41
			_, _ = io.WriteString(w, "\n\n\t\t")
//line http/html/dial.index.ego:42
			if len(tmpl.Dials) > 0 {
//line http/html/dial.index.ego:43
				_, _ = io.WriteString(w, "\n\t\t\t<div class=\"card mb-3\">\n\t\t\t\t<div class=\"card-header bg-light\">\n\t\t\t\t\t<div class=\"row flex-between-center\">\n\t\t\t\t\t\t<div class=\"col-6 col-sm-auto\">\n\t\t\t\t\t\t\t<h5 class=\"mb-0 py-2 py-xl-0\">Dials</h5>\n\t\t\t\t\t\t</div>\n\n\t\t\t\t\t\t<div class=\"col-6 col-sm-auto ml-auto text-right pl-0\">\n\t\t\t\t\t\t\t<a href=\"/dials/new\" class=\"btn btn-falcon-default btn-sm btn-new-dial\" role=\"button\">\n\t\t\t\t\t\t\t\t<span class=\"fas fa-plus mr-1\"></span> New\n\t\t\t\t\t\t\t</a>\n\n\t\t\t\t\t\t\t<a href=\"/dials.csv\" target=\"_blank\" class=\"btn btn-falcon-default btn-sm\" type=\"button\">\n\t\t\t\t\t\t\t\t<span class=\"fas fa-external-link-alt mr-1\"></span> Export\n\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\n\t\t\t\t<div class=\"card-body px-0 py-0\">\n\t\t\t\t\t<div class=\"table-responsive scrollbar\">\n\t\t\t\t\t\t<table class=\"table table-sm table-dials fs--1 mb-0\">\n\t\t\t\t\t\t\t<thead class=\"bg-200 text-900\">\n\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t<th class=\"sort pr-1 align-middle white-space-nowrap\" data-sort=\"name\">\n\t\t\t\t\t\t\t\t\t\tName\n\t\t\t\t\t\t\t\t\t</th>\n\n\t\t\t\t\t\t\t\t\t<th class=\"sort pr-1 align-middle white-space-nowrap\" data-sort=\"user.name\">\n\t\t\t\t\t\t\t\t\t\tCreated by\n\t\t\t\t\t\t\t\t\t</th>\n\n\t\t\t\t\t\t\t\t\t<th class=\"sort pr-1 align-middle white-space-nowrap\" data-sort=\"value\">\n\t\t\t\t\t\t\t\t\t\tWTF Level\n\t\t\t\t\t\t\t\t\t</th>\n\n\t\t\t\t\t\t\t\t\t<th class=\"sort pr-1 align-middle white-space-nowrap\" data-sort=\"updated_at\">\n\t\t\t\t\t\t\t\t\t\tLast Updated\n\t\t\t\t\t\t\t\t\t</th>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t</thead>\n\n\n\t\t\t\t\t\t\t<tbody class=\"list\">\n\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:88
				for _, dial := range tmpl.Dials {
//line http/html/dial.index.ego:89
					_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<th class=\"align-middle white-space-nowrap dial-name\">\n\t\t\t\t\t\t\t\t\t\t\t<a href=\"/dials/")
//line http/html/dial.index.ego:91
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(dial.ID)))
//line http/html/dial.index.ego:91
					_, _ = io.WriteString(w, "\">\n\t\t\t\t\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:92
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(dial.Name)))
//line http/html/dial.index.ego:93
					_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t\t\t\t</th>\n\n\t\t\t\t\t\t\t\t\t\t<td class=\"align-middle white-space-nowrap dial-user-name\">\n\t\t\t\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:97
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(dial.User.Name)))
//line http/html/dial.index.ego:98
					_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t\t\t\t</td>\n\n\t\t\t\t\t\t\t\t\t\t<td class=\"align-middle fs-0 white-space-nowrap dial-value\">\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge badge rounded-pill badge-soft-success\">\n\t\t\t\t\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:102
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(dial.Value)))
//line http/html/dial.index.ego:103
					_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t\t\t\t\t</span>\n\t\t\t\t\t\t\t\t\t\t</td>\n\n\t\t\t\t\t\t\t\t\t\t<td class=\"align-middle white-space-nowrap\">\n\t\t\t\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:107
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(humanize.Time(dial.UpdatedAt))))
//line http/html/dial.index.ego:108
					_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t")
//line http/html/dial.index.ego:110
				}
//line http/html/dial.index.ego:111
				_, _ = io.WriteString(w, "\n\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t</table>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\n\t\t\t\t<div class=\"card-footer\">\n\t\t\t\t\t")
//line http/html/dial.index.ego:118
				{
					var EGO Pagination
					EGO.URL = tmpl.URL
					EGO.Limit = tmpl.Filter.Limit
					EGO.Offset = tmpl.Filter.Offset
					EGO.N = tmpl.N
					EGO.Render(ctx, w)
				}
//line http/html/dial.index.ego:124
				_, _ = io.WriteString(w, "\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t")
//line http/html/dial.index.ego:126
			}
//line http/html/dial.index.ego:127
			_, _ = io.WriteString(w, "\n\t</div>\n")
		}
		EGO.Render(ctx, w)
	}
//line http/html/dial.index.ego:129
	_, _ = io.WriteString(w, "\n")
//line http/html/dial.index.ego:129
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
