// Generated by ego.
// DO NOT EDIT

//line http/html/error.ego:1

package html

import (
	"context"
	"fmt"
	"html"
	"io"
)

type ErrorTemplate struct {
	StatusCode int
	Header     string
	Message    string
}

func (tmpl *ErrorTemplate) Render(ctx context.Context, w io.Writer) {

//line http/html/error.ego:11
	{
		var EGO App
		EGO.Chromeless = true
		EGO.Yield = func() {
//line http/html/error.ego:12
			_, _ = io.WriteString(w, "\n\n<main class=\"main\" id=\"top\">\n\t<div class=\"container\" data-layout=\"container\">\n\t\t<div class=\"row flex-center min-vh-100 py-6 text-center\">\n\t\t\t<div class=\"col-sm-10 col-md-8 col-lg-6 col-xxl-5\">\n\t\t\t\t<a class=\"d-flex flex-center mb-4\" href=\"../../index.html\">\n\t\t\t\t\t<span class=\"font-sans-serif font-weight-bolder fs-5 d-inline-block\">WTF Dial</span>\n\t\t\t\t</a>\n\n\t\t\t\t<div class=\"card\">\n\t\t\t\t\t<div class=\"card-body p-4 p-sm-5\">\n\t\t\t\t\t\t<div class=\"font-weight-black lh-1 text-300 fs-error\">\n\t\t\t\t\t\t\t")
//line http/html/error.ego:24
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.StatusCode)))
//line http/html/error.ego:25
			_, _ = io.WriteString(w, "\n\t\t\t\t\t\t</div>\n\n\t\t\t\t\t\t<p class=\"lead mt-4 text-800 font-sans-serif font-weight-semi-bold\">\n\t\t\t\t\t\t\t")
//line http/html/error.ego:28
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.Header)))
//line http/html/error.ego:29
			_, _ = io.WriteString(w, "\n\t\t\t\t\t\t</p>\n\n\t\t\t\t\t\t<hr />\n\n\t\t\t\t\t\t<p>\n\t\t\t\t\t\t\t")
//line http/html/error.ego:34
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(tmpl.Message)))
//line http/html/error.ego:35
			_, _ = io.WriteString(w, "\n\t\t\t\t\t\t</p>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</main>\n\n")
		}
		EGO.Render(ctx, w)
	}
//line http/html/error.ego:44
	_, _ = io.WriteString(w, "\n")
//line http/html/error.ego:44
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
