// Generated by ego.
// DO NOT EDIT

//line http/html/settings.ego:1

package html

import (
	"context"
	"fmt"
	"html"
	"io"

	"github.com/benbjohnson/wtf"
)

type SettingsTemplate struct{}

func (tmpl *SettingsTemplate) Render(ctx context.Context, w io.Writer) {
	user := wtf.UserFromContext(ctx)

//line http/html/settings.ego:12
	{
		var EGO App
		EGO.Yield = func() {
//line http/html/settings.ego:13
			_, _ = io.WriteString(w, "\n\t<div class=\"content\">\n\t\t<div class=\"card mb-3\">\n\t\t\t<div class=\"card-body\">\n\t\t\t\t<h3 class=\"mb-0\">\n\t\t\t\t\tSettings\n\t\t\t\t</h3>\n\t\t\t</div>\n\t\t</div>\n\n\t\t<div class=\"card mb-3\">\n\t\t\t<div class=\"card-body bg-light\">\n\t\t\t\t<div class=\"row\">\n\t\t\t\t\t<div class=\"col mb-3\">\n\t\t\t\t\t\t<label class=\"form-label\" for=\"api_key\">API Key</label>\n\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"api_key\" name=\"api_key\" value=\"")
//line http/html/settings.ego:27
			_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(user.APIKey)))
//line http/html/settings.ego:27
			_, _ = io.WriteString(w, "\" readonly/>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n")
		}
		EGO.Render(ctx, w)
	}
//line http/html/settings.ego:34
	_, _ = io.WriteString(w, "\n")
//line http/html/settings.ego:34
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
